require("tigertm.config.treesitter")
require("tigertm.config.lsp-zero")
require("tigertm.config.lualine")
require("tigertm.config.rust-tools")
require("tigertm.config.autopairs")
require("tigertm.config.nvim-tree")
